using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameDataManager : MonoBehaviour
{
    // Static reference to the GameDataManager
    public static GameDataManager instance;
    
    // List of items
    public List<Item> items = new List<Item>();

    // Initialize the list of items
    void Start()
    {
        
        items.Add(new Item("Cell Key", 0, true, true));
        items.Add(new Item("Staff Key", 1, true, true));
        items.Add(new Item("Utility Key", 2, true, true));
        items.Add(new Item("Enterance Key", 3, true, true));
        items.Add(new Item("Work Key", 4, true, true));
        items.Add(new Item("Plastic Cell Key", 5, true, false));
        items.Add(new Item("Plastic Staff Key", 6, true, false));
        items.Add(new Item("Plastic Utility Key", 7, true, false));
        items.Add(new Item("Plastic Enterance Key", 8, true, false));
        items.Add(new Item("Plastic Work Key", 9, true, false));
        items.Add(new Item("Flimsy Shovel", 10, true, false));
        items.Add(new Item("Lightweight Shovel", 11, true, false));
        items.Add(new Item("Sturdy Shovel", 12, true, false));
        items.Add(new Item("Flimsy Pickaxe", 13, true, false));
        items.Add(new Item("Lightweight Pickaxe", 14, true, false));
        items.Add(new Item("Sturdy Pickaxe", 15, true, false));
        items.Add(new Item("Flimsy Cutters", 16, true, false));
        items.Add(new Item("Lightweight Cutters", 17, true, false));
        items.Add(new Item("Sturdy Cutters", 18, true, false));
        items.Add(new Item("Multitool", 19, true, false));
        items.Add(new Item("Screwdriver", 20, true, false));
        items.Add(new Item("Powered Screwdriver", 21, true, false));
        items.Add(new Item("Trowel", 22, true, false));
        items.Add(new Item("Cutting Floss", 23, true, false));
        items.Add(new Item("File", 24, true, false));
        items.Add(new Item("Crowbar", 25, true, false));
        items.Add(new Item("Plastic Fork", 26, false, false));
        items.Add(new Item("Plastic Knife", 27, false, false));
        items.Add(new Item("Plastic Spoon", 28, false, false));
        items.Add(new Item("Inmate Outfit", 29, false, false));
        items.Add(new Item("Cushioned Inmate Outfit", 30, true, false));
        items.Add(new Item("Padded Inmate Outfit", 31, true, false));
        items.Add(new Item("Plated Inmate Outfit", 32, true, false));
        items.Add(new Item("POW Outfit", 33, false, false));
        items.Add(new Item("Cushioned POW Outfit", 34, true, false));
        items.Add(new Item("Padded POW Outfit", 35, true, false));
        items.Add(new Item("Plated POW Outfit", 36, true, false));
        items.Add(new Item("Dirty Inmate Outfit", 37, false, false));
        items.Add(new Item("Dirty Guard Outfit", 38, true, false));
        items.Add(new Item("Guard Outfit", 39, true, false));
        items.Add(new Item("Elf Outfit", 40, false, false));
        items.Add(new Item("Cushioned Elf Outfit", 41, true, false));
        items.Add(new Item("Padded Elf Outfit", 42, true, false));
        items.Add(new Item("Plated Elf Outfit", 43, true, false));
        items.Add(new Item("Guard Elf Outfit", 44, true, false));
        items.Add(new Item("Tux Outfit", 45, false, false));
        items.Add(new Item("Cushioned Tux Outfit", 46, true, false));
        items.Add(new Item("Padded Tux Outfit", 47, true, false));
        items.Add(new Item("Plated Tux Outfit", 48, true, false));
        items.Add(new Item("Henchman Outfit", 49, true, false));
        items.Add(new Item("Prisoner Outfit", 50, false, false));
        items.Add(new Item("Cushioned Prisoner Outfit", 51, true, false));
        items.Add(new Item("Padded Prisoner Outfit", 52, true, false));
        items.Add(new Item("Plated Prisoner Outfit", 53, true, false));
        items.Add(new Item("Soldier Outfit", 54, true, false));
        items.Add(new Item("Baseball Bat", 55, true, false));
        items.Add(new Item("Baton", 56, true, false));
        items.Add(new Item("Broom", 57, false, false));
        items.Add(new Item("Comb Blade", 58, true, false));
        items.Add(new Item("Comb Shiv", 59, true, false));
        items.Add(new Item("Hammer", 60, true, false));
        items.Add(new Item("Hoe", 61, false, false));
        items.Add(new Item("Knuckle Duster", 62, true, false));
        items.Add(new Item("Mop", 63, false, false));
        items.Add(new Item("Nunchuks", 64, true, false));
        items.Add(new Item("Pillow", 65, false, false));
        items.Add(new Item("Sock Mace", 66, true, false));
        items.Add(new Item("Spiked Bat", 67, true, false));
        items.Add(new Item("Super Sock Mace", 68, true, false));
        items.Add(new Item("Toothbrush Shiv", 69, true, false));
        items.Add(new Item("Whip", 70, true, false));
        items.Add(new Item("Wooden Bat", 71, true, false));
        items.Add(new Item("Glass Shank", 72, true, false));
        items.Add(new Item("Bar of Chocolate", 73, false, false));
        items.Add(new Item("Battery", 74, false, false));
        items.Add(new Item("Bed Dummy", 75, true, false));
        items.Add(new Item("Bed Sheet", 76, false, false));
        items.Add(new Item("Book", 77, false, false));
        items.Add(new Item("Bottle of Medicine", 78, false, false));
        items.Add(new Item("Bottle of Sleeping Pills", 79, true, false));
        items.Add(new Item("Candle", 80, false, false));
        items.Add(new Item("Cell Key Mold", 81, true, false));
        items.Add(new Item("Comb", 82, false, false));
        items.Add(new Item("Contraband Pouch", 83, true, false));
        items.Add(new Item("Cooked Food", 84, false, false));
        items.Add(new Item("Crafting Note", 85, true, false));
        items.Add(new Item("Cup", 86, false, false));
        items.Add(new Item("Cup of Molten Chocolate", 87, true, false));
        items.Add(new Item("Dead Rat", 88, false, false));
        items.Add(new Item("Dental Floss", 89, false, false));
        items.Add(new Item("DIY Tattoo Kit", 90, false, false));
        items.Add(new Item("DoDo Donut", 91, false, false));
        items.Add(new Item("Durable Contraband Pouch", 92, true, false));
        items.Add(new Item("Entrance Key Mold", 93, true, false));
        items.Add(new Item("Fabric", 94, false, false));
        items.Add(new Item("Fake Fence", 95, true, false));
        items.Add(new Item("Fake Vent Cover", 96, true, false));
        items.Add(new Item("Fake Wall Block", 97, true, false));
        items.Add(new Item("Foil", 98, true, false));
        items.Add(new Item("Game Set", 99, false, false));
        items.Add(new Item("Glass Shark", 100, true, false));
        items.Add(new Item("Grapple Head", 101, true, false));
        items.Add(new Item("Grappling Hook", 102, true, false));
        items.Add(new Item("Infirmary Overalls", 103, true, false));
        items.Add(new Item("Jar of Ink", 104, false, false));
        items.Add(new Item("Length of Rope", 105, true, false));
        items.Add(new Item("Letter", 107, false, false));
        items.Add(new Item("Lighter", 108, false, false));
        items.Add(new Item("Magazine", 109, false, false));
        items.Add(new Item("Medkit", 110, false, false));
        items.Add(new Item("Molten Plastic", 111, true, false));
        items.Add(new Item("Nails", 112, false, false));
        items.Add(new Item("Needle and Thread", 113, false, false));
        items.Add(new Item("Pack of Mints", 114, false, false));
        items.Add(new Item("Pack of Playing Cards", 115, false, false));
        items.Add(new Item("Blue Package", 116, false, false));
        items.Add(new Item("Red Package", 117, false, false));
        items.Add(new Item("Green Package", 118, false, false));
        items.Add(new Item("Paper Clip", 119, false, false));
        items.Add(new Item("Paper Mache", 120, true, false));
        items.Add(new Item("Penarium Barrel", 121, false, false));
        items.Add(new Item("Plunger", 122, false, false));
        items.Add(new Item("Dirt", 123, true, true)); //random dirt lmao
        items.Add(new Item("Poster", 124, false, false));
        items.Add(new Item("Radio Reciever", 125, false, false));
        items.Add(new Item("Razor Blade", 126, false, false));
        items.Add(new Item("Roll of Duct Tape", 127, true, false));
        items.Add(new Item("Roll of Toilet Paper", 128, false, false));
        items.Add(new Item("Shaving Cream", 129, false, false));
        items.Add(new Item("Sheet of Metal", 130, true, false));
        items.Add(new Item("Sheet Rope", 131, true, false));
        items.Add(new Item("Shorts", 132, false, false));
        items.Add(new Item("Small Speaker", 133, true, false));
        items.Add(new Item("Soap", 134, false, false));
        items.Add(new Item("Sock", 135, false, false));
        items.Add(new Item("Spatula", 136, true, false));
        items.Add(new Item("Stepladder", 137, true, false));
        items.Add(new Item("Stinger Strip", 138, true, false));
        items.Add(new Item("Timber", 139, true, false));
        items.Add(new Item("Timber Brace", 140, true, false));
        items.Add(new Item("Tool Handle", 141, true, false));
        items.Add(new Item("Toothbrush", 142, false, false));
        items.Add(new Item("Tub of Bleach", 143, false, false));
        items.Add(new Item("Tub of Talcum Powder", 144, false, false));
        items.Add(new Item("Tube of Super Glue", 145, false, false));
        items.Add(new Item("Tube of Toothpaste", 146, false, false));
        items.Add(new Item("Uncooked Food", 147, false, false));
        items.Add(new Item("Underpants", 148, false, false));
        items.Add(new Item("Unvarnished Chair", 149, false, false));
        items.Add(new Item("Utility Key Mold", 150, true, false));
        items.Add(new Item("Vent Cover", 151, true, true));
        items.Add(new Item("Vest", 152, false, false));
        items.Add(new Item("Wad of Putty", 153, true, false));
        items.Add(new Item("Wall Block", 154, true, true));
        items.Add(new Item("Watch", 155, false, false));
        items.Add(new Item("Wire", 156, false, false));
        items.Add(new Item("Work Key Mold", 157, true, false));
        items.Add(new Item("Worms Game", 158, false, false));
        items.Add(new Item("Zipline Hook", 159, true, false));
        items.Add(new Item("Bulbs", 160, true, false)); // prison specific items
        items.Add(new Item("Candy Cane Lever", 161, true, false));
        items.Add(new Item("Charcoal", 162, true, false));
        items.Add(new Item("Chisel", 163, true, false));
        items.Add(new Item("Cork", 164, false, false));
        items.Add(new Item("Corrugated Iron", 165, true, false));
        items.Add(new Item("Dirty Glass", 166, true, false));
        items.Add(new Item("Empty Bottle", 167, false, false));
        items.Add(new Item("Explosive Compound", 168, true, false));
        items.Add(new Item("Explosive Mix", 169, true, false));
        items.Add(new Item("Fairy Lights", 170, true, false));
        items.Add(new Item("Fake Fingerprint", 171, true, false));
        items.Add(new Item("Fertilizer", 172, true, false));
        items.Add(new Item("Flamethrower", 173, true, false));
        items.Add(new Item("Flashlight", 174, false, false)); //random flashlight lmao
        items.Add(new Item("Fuel", 175, true, false));
        items.Add(new Item("Glitter", 176, true, false));
        items.Add(new Item("Halogen Bulb", 177, true, false));
        items.Add(new Item("Hat", 178, false, false)); // random hat lolllll
        items.Add(new Item("High Beam Flashlight", 179, true, false));
        items.Add(new Item("Juicy Cooked Carrots", 180, false, false));
        items.Add(new Item("Keycard", 181, false, false));
        items.Add(new Item("License Plate", 182, true, false)); //random license plate lomaoamoma
        items.Add(new Item("Magnet", 183, false, false));
        items.Add(new Item("Magnetized Needle", 184, false, false));
        items.Add(new Item("Makeshift Compass", 185, true, false));
        items.Add(new Item("Makeshift Explosive Round", 186, true, false));
        items.Add(new Item("Makeshift Fuse", 187, true, false));
        items.Add(new Item("Makeshift Raft", 188, true, false));
        items.Add(new Item("Makeshift Tank Barrel", 189, true, false));
        items.Add(new Item("Makeshift Tank Firing Base", 190, true, false));
        items.Add(new Item("Makeshift Tank Turret", 191, true, false));
        items.Add(new Item("Memoir Tapes", 192, true, false));
        items.Add(new Item("Metal Cone", 193, true, false));
        items.Add(new Item("Metal Rimmed Hat", 194, true, false));
        items.Add(new Item("Metal Tube", 195, true, false));
        items.Add(new Item("Mixing Container", 196, true, false));
        items.Add(new Item("Naughty Letter", 197, false, false));
        items.Add(new Item("Navigation Lighting", 198, true, false));
        items.Add(new Item("Needle", 199, false, false));
        items.Add(new Item("Nice Letter", 200, false, false));
        items.Add(new Item("Presents", 201, true, false));
        items.Add(new Item("Raft Base", 202, true, false));
        items.Add(new Item("Raw Nasty Carrots", 203, false, false));
        items.Add(new Item("Red Herring", 204, false, false));
        items.Add(new Item("Reindeer Bowl", 205, false, false));
        items.Add(new Item("Sticky Tape", 206, false, false));
        items.Add(new Item("Stun Rod", 207, true, false));
        items.Add(new Item("Tape Player", 208, true, false));
        items.Add(new Item("Taper", 209, true, false));
        items.Add(new Item("Thruster", 210, true, false));
        items.Add(new Item("Tinsel", 211, true, false));
        items.Add(new Item("Voice Recording", 212, true, false));
        items.Add(new Item("Weak Fingerprint", 213, true, false));
        items.Add(new Item("Wooden Ball", 214, false, false));
        items.Add(new Item("Wooden Block", 215, false, false));
        items.Add(new Item("Wooden Doll", 216, false, false));
        items.Add(new Item("Wooden Joystick", 217, false, false));
        items.Add(new Item("Wooden Scooter", 218, false, false));
        items.Add(new Item("Work Hat", 219, false, false));
        items.Add(new Item("Wrapping Paper", 220, true, false));
        items.Add(new Item("Cookie", 221, false, false));
        items.Add(new Item("Deluxe Toilet Roll", 222, false, false));
        items.Add(new Item("DVD", 223, false, false));
        items.Add(new Item("Hand Cream", 224, false, false));
        items.Add(new Item("Hand Fan", 225, false, false));
        items.Add(new Item("Muffin", 226, false, false));
        items.Add(new Item("Pedicure Kit", 227, false, false));
        items.Add(new Item("Postcard", 228, false, false));
        items.Add(new Item("Silk Handkerchif", 229, false, false));
        items.Add(new Item("Sponge", 230, false, false));
        items.Add(new Item("Teddy Bear", 231, false, false));
        items.Add(new Item("TV Remote", 232, false, false));
        items.Add(new Item("Bomb Surprise", 233, true, false));
        items.Add(new Item("Cutting Laser Watch", 234, true, false));
        items.Add(new Item("Fake Decorated Egg", 235, false, false));
        items.Add(new Item("Fake Shoe", 236, false, false));
        items.Add(new Item("Garotting Wire Watch", 237, true, false));
        items.Add(new Item("Hairspray", 238, true, false));
        items.Add(new Item("Pork Pie Hat", 239, false, false));
        items.Add(new Item("Sharp Tea Tray", 240, true, false));
        items.Add(new Item("Shoe Knife", 241, true, false));
        items.Add(new Item("Stun Pen", 242, true, false));
        items.Add(new Item("Aftershave", 243, false, false));
        items.Add(new Item("Sovereign Ring", 244, false, false));
        items.Add(new Item("Trash Bag", 245, false, false));
        items.Add(new Item("Balsa Wood", 246, true, false));
        items.Add(new Item("Sail", 247, true, false));
        items.Add(new Item("Bananas", 248, false, false));
        items.Add(new Item("Coconut", 249, false, false));
        items.Add(new Item("Exotic Feather", 250, false, false));
        items.Add(new Item("Green Herb", 251, false, false));
        items.Add(new Item("ID Papers", 252, true, false));
        items.Add(new Item("Mango", 253, false, false));
        items.Add(new Item("Red Herb", 254, false, false));
        items.Add(new Item("Tribal Drum", 255, false, false));
        items.Add(new Item("Unsigned ID Papers", 256, true, false));
        items.Add(new Item("Vines", 257, false, false));
        items.Add(new Item("Cracker", 258, true, false));
        items.Add(new Item("Giant Lollipop", 259, true, false));
        items.Add(new Item("Mince Pie", 260, false, false));
        items.Add(new Item("Stocking", 261, false, false));
        items.Add(new Item("Burrito", 262, false, false));
        items.Add(new Item("Poncho", 263, false, false));
        items.Add(new Item("Red Chili", 264, false, false));
        items.Add(new Item("Sand", 265, true, true));
        items.Add(new Item("Somberero", 266, false, false));
        items.Add(new Item("Dog Tag", 267, false, false));
        items.Add(new Item("Family Photo", 268, false, false));
        items.Add(new Item("Pocket Watch", 269, false, false));
        items.Add(new Item("Service Medal", 270, false, false));
    }
}
